# render.yaml - Configuration for Bizmark.id SaaS Platform
# Documentation: https://render.com/docs/blueprint-spec

# Automatic preview environments with expiration
previews:
  generation: automatic
  expireAfterDays: 7  # Auto-expire preview environments after 7 days without updates

services:
  # Main Backend API Service
  - type: web
    name: bizmark-api
    runtime: node
    region: singapore
    plan: starter
    buildCommand: ./build.sh
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /api/v1/health/ready
    autoDeployTrigger: commit  # Modern replacement for autoDeploy
    branch: main
    preDeployCommand: cd backend && npm run db:migrate  # Run migrations before deploy
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70
      targetCPUPercent: 70
    buildFilter:
      paths:
        - backend/**/*.ts
        - backend/**/*.json
        - package.json
        - build.sh
      ignoredPaths:
        - backend/**/*.spec.ts
        - backend/**/*.test.ts
    envVars:
      # Application settings
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api
      - key: API_VERSION
        value: v1
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_DOCS
        value: "true"
        
      # Security settings
      - key: JWT_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: MAX_LOGIN_ATTEMPTS
        value: "5"
      - key: LOCKOUT_TIME
        value: "900000"
        
      # Performance settings
      - key: THROTTLE_TTL
        value: "60"
      - key: THROTTLE_LIMIT
        value: "100"
      - key: DB_POOL_MIN
        value: "5"
      - key: DB_POOL_MAX
        value: "20"
      - key: HEALTH_CHECK_TIMEOUT
        value: "5000"
      - key: METRICS_ENABLED
        value: "true"
        
      # Upload settings
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: ALLOWED_FILE_TYPES
        value: "pdf,doc,docx,jpg,jpeg,png,gif"
        
      # CORS settings
      - key: CORS_CREDENTIALS
        value: "true"
        
      # Database connection (auto-configured by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: bizmark-db
          property: connectionString
          
      # Redis connection (set manually in dashboard)
      - key: REDIS_URL
        sync: false
        
      # Security secrets (set manually in dashboard)
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
        
      # Load common environment variables
      - fromGroup: bizmark-common-env
      - fromGroup: bizmark-security-env
      
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Redis Service for Caching and Job Queue
  - type: keyvalue  # Best practice: use 'keyvalue' type instead of 'redis'
    name: bizmark-redis
    region: singapore
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (production ready)
    maxmemoryPolicy: volatile-lru

  # Scheduled Jobs Service (Optional)
  - type: cron
    name: bizmark-jobs
    runtime: node
    region: singapore  # Match region with other services
    schedule: '0 */6 * * *'  # Every 6 hours
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm run jobs:run
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bizmark-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: bizmark-redis
          property: connectionString
      - key: NODE_ENV
        value: production
      - fromGroup: bizmark-common-env

databases:
  - name: bizmark-db
    databaseName: bizmark_production
    user: bizmark_user
    plan: standard
    postgresMajorVersion: "15"  # Explicitly specify version
    region: singapore
    diskSizeGB: 15  # Explicitly define disk size
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all (production ready)
    # For future scaling, these can be uncommented when needed
    # readReplicas:
    #   - name: bizmark-db-replica
    # highAvailability:
    #   enabled: true

# Common Environment Variables
envVarGroups:
  - name: bizmark-common-env
    envVars:
      - key: APP_NAME
        value: "Bizmark.id"
      - key: SUPPORT_EMAIL
        value: "support@bizmark.id"
      - key: ENVIRONMENT
        value: "production"
      - key: PLATFORM_VERSION
        value: "1.0.0"
  
  # Security-related environment variables
  - name: bizmark-security-env
    envVars:
      - key: SECURE_COOKIES
        value: "true"
      - key: SSL_ENABLED
        value: "true"
