# render.yaml - Configuration for Render.com deployment
# Documentation: https://render.com/docs/blueprint-spec

services:
  - name: bizmark-api
    type: web
    env: node
    region: singapore
    plan: starter
    buildCommand: ./build.sh
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /api/v1/health/ready
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api
      - key: API_VERSION
        value: v1
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_DOCS
        value: "true"
      - key: JWT_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: MAX_LOGIN_ATTEMPTS
        value: "5"
      - key: LOCKOUT_TIME
        value: "900000"
      - key: THROTTLE_TTL
        value: "60"
      - key: THROTTLE_LIMIT
        value: "100"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: ALLOWED_FILE_TYPES
        value: "pdf,doc,docx,jpg,jpeg,png,gif"
      - key: DB_POOL_MIN
        value: "5"
      - key: DB_POOL_MAX
        value: "20"
      - key: HEALTH_CHECK_TIMEOUT
        value: "5000"
      - key: METRICS_ENABLED
        value: "true"
      - key: CORS_CREDENTIALS
        value: "true"
      # Database connection (auto-configured by Render)
      - key: DATABASE_URL
        fromDatabase:
          name: bizmark-db
          property: connectionString
      # Redis connection (auto-configured by Render)  
      - key: REDIS_URL
        fromService:
          name: bizmark-redis
          type: redis
          envVarKey: REDIS_URL
      # Secrets (set manually in Render dashboard)
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
    autoDeploy: true

  - name: bizmark-redis
    type: redis
    region: singapore
    plan: starter
    ipAllowList: []

databases:
  - name: bizmark-db
    databaseName: bizmark_production
    user: bizmark_user
    plan: starter
    region: singapore
