# render.yaml - Configuration for Render.com deployment
services:
  - name: bizmark-api
    type: web
    env: node
    region: singapore # Pilih region yang dekat dengan pengguna di Indonesia
    plan: starter # Free tier untuk testing, upgrade ke paid plan untuk production
    buildCommand: cd backend && npm install --no-audit && npm run build
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /api/v1/health/live # Endpoint sederhana untuk health check
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          name: bizmark-api
          type: web
          envVarKey: PORT
      - key: API_PREFIX
        value: api
      - key: API_VERSION
        value: v1
      - key: LOG_LEVEL
        value: info
      - key: ENABLE_DOCS
        value: true
      - key: JWT_EXPIRES_IN
        value: 3600
      - key: BCRYPT_ROUNDS
        value: 14
      - key: MAX_LOGIN_ATTEMPTS
        value: 3
      - key: LOCKOUT_TIME
        value: 1800000
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 50
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_FILE_TYPES
        value: pdf,doc,docx,jpg,jpeg,png
      - key: DB_POOL_MIN
        value: 5
      - key: DB_POOL_MAX
        value: 20
      - key: HEALTH_CHECK_TIMEOUT
        value: 5000
      - key: METRICS_ENABLED
        value: true
      # Secrets - akan diatur manual di dashboard Render
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: REDIS_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: API_URL
        sync: false
      - key: CORS_ORIGINS
        sync: false
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1

databases:
  - name: bizmark-db
    plan: starter # Free PostgreSQL untuk testing
    ipAllowList: [] # Allow all IPs (secure dengan username/password)

  - name: bizmark-redis
    type: redis
    plan: starter # Free Redis untuk testing
    ipAllowList: []
