name: Docker Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
          
      - name: Install dependencies
        run: |
          cd backend
          npm ci
          
      - name: Build application
        run: |
          cd backend
          npm run build
          
      - name: Run tests
        run: |
          cd backend
          npm test
          
      - name: Deploy to VPS with Docker
        uses: appleboy/ssh-action@v0.1.5
        with:
          # VPS connection secrets - configure in GitHub repository settings
          host: ${{ secrets.VPS_HOST }}          # VPS IP address
          username: ${{ secrets.VPS_USERNAME }}  # SSH username
          key: ${{ secrets.VPS_SSH_KEY }}        # SSH private key
          port: ${{ secrets.VPS_PORT }}          # SSH port (default: 22)
          script: |
            cd /var/www/bizmark.id
            
            # Pull latest code from GitHub
            git pull origin main
            
            # Stop existing containers gracefully
            docker-compose -f docker-compose.prod.yml down --timeout 30
            
            # Build new Docker image
            docker build -t bizmark-api:latest -f backend/Dockerfile backend/
            
            # Start all services with docker-compose
            docker-compose -f docker-compose.prod.yml up -d
            
            # Wait for services to be healthy
            echo "Waiting for services to start..."
            sleep 30
            
            # Verify deployment
            docker ps --filter "name=bizmark" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
            
            # Test API health endpoint
            curl -f http://localhost:3000/api/v1/health || echo "Health check failed"
            
            # Clean up unused Docker images to save space
            docker image prune -f
            
            # Log successful deployment
            echo "Docker deployment completed successfully at $(date)" >> /var/log/bizmark-deployments.log
